### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by henriquenasc** [DwarfTecnologia/Curso-Flask-Youtube-Free#1]
Olá! Ótimo curso parabéns. Estou acompanhando e gostando bastante, porem estou com um erro na aula 8 MVC². Quando eu tento executar `python run.py runserver` tenho o seguinte retorno:

> Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from app import manager
ModuleNotFoundError: No module named 'app'

A estrutura ta a seguinte: pasta app2 -> controllers, views, models, static, venv,  __init__.py

fora, um nivel acima tem -> run.py e config.py

Não estou entendendo como ele não esta conseguindo encontrar o modulo.
Poderia me ajudar?

**Comment by henriquenasc** [comment]
Resolvido

Era porque eu não tinha criado uma pasta em que todas as outras ficariam dentro.

Ex:
 curso-flask
      --- app2
           --- views
           --- controllers
           --- models
           --- __init__.py
      --- run.py
      --- config.py

Como antes não estava tudo dentro da pasta curso-flask ele não estava encontrado ou reconhecendo a pasta app2 como um modulo.

**Comment by MarcusMann** [comment]
Lembre-se que tem que ser __init__.py e não init.py.
